/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace Vault {
  export type LockedTokenStruct = {
    amount: PromiseOrValue<BigNumberish>;
    unlockTime: PromiseOrValue<BigNumberish>;
    released: PromiseOrValue<boolean>;
  };

  export type LockedTokenStructOutput = [BigNumber, BigNumber, boolean] & {
    amount: BigNumber;
    unlockTime: BigNumber;
    released: boolean;
  };
}

export interface PlayToEarnVaultInterface extends utils.Interface {
  functions: {
    "currentVestingIndex()": FunctionFragment;
    "depositRecords(string)": FunctionFragment;
    "depositTokens(uint256,address)": FunctionFragment;
    "getAvailableAmountForWithdraw()": FunctionFragment;
    "getVestingData()": FunctionFragment;
    "lockTokens(uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "playToEarnServiceAddress()": FunctionFragment;
    "playerDepositTokensToGame(string,uint256)": FunctionFragment;
    "playerWithdrawTokensFromGame(address[],uint256[])": FunctionFragment;
    "proxyAddress()": FunctionFragment;
    "releasedAmount()": FunctionFragment;
    "setPlayToEarnServiceAddress(address)": FunctionFragment;
    "soulsTokenAddress()": FunctionFragment;
    "tokenVestings(uint256)": FunctionFragment;
    "totalWithdrawnAmount()": FunctionFragment;
    "vaultName()": FunctionFragment;
    "withdrawTokens(address[],uint256[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "currentVestingIndex"
      | "depositRecords"
      | "depositTokens"
      | "getAvailableAmountForWithdraw"
      | "getVestingData"
      | "lockTokens"
      | "playToEarnServiceAddress"
      | "playerDepositTokensToGame"
      | "playerWithdrawTokensFromGame"
      | "proxyAddress"
      | "releasedAmount"
      | "setPlayToEarnServiceAddress"
      | "soulsTokenAddress"
      | "tokenVestings"
      | "totalWithdrawnAmount"
      | "vaultName"
      | "withdrawTokens"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "currentVestingIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositRecords",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "depositTokens",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableAmountForWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVestingData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockTokens",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "playToEarnServiceAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "playerDepositTokensToGame",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "playerWithdrawTokensFromGame",
    values: [PromiseOrValue<string>[], PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "proxyAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "releasedAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPlayToEarnServiceAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "soulsTokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenVestings",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "totalWithdrawnAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "vaultName", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawTokens",
    values: [PromiseOrValue<string>[], PromiseOrValue<BigNumberish>[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "currentVestingIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableAmountForWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVestingData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockTokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "playToEarnServiceAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playerDepositTokensToGame",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playerWithdrawTokensFromGame",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxyAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releasedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlayToEarnServiceAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "soulsTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenVestings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalWithdrawnAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaultName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawTokens",
    data: BytesLike
  ): Result;

  events: {
    "DepositTokens(uint256,uint256)": EventFragment;
    "PlayerDeposit(uint256,string,uint256)": EventFragment;
    "PlayerWithdraw(uint256,address[],uint256[])": EventFragment;
    "ReleaseVesting(uint256,uint256)": EventFragment;
    "Withdraw(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DepositTokens"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PlayerDeposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PlayerWithdraw"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReleaseVesting"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdraw"): EventFragment;
}

export interface DepositTokensEventObject {
  date: BigNumber;
  _amount: BigNumber;
}
export type DepositTokensEvent = TypedEvent<
  [BigNumber, BigNumber],
  DepositTokensEventObject
>;

export type DepositTokensEventFilter = TypedEventFilter<DepositTokensEvent>;

export interface PlayerDepositEventObject {
  timestamp: BigNumber;
  playfabTxId: string;
  amount: BigNumber;
}
export type PlayerDepositEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  PlayerDepositEventObject
>;

export type PlayerDepositEventFilter = TypedEventFilter<PlayerDepositEvent>;

export interface PlayerWithdrawEventObject {
  timestamp: BigNumber;
  playerWallet: string[];
  amount: BigNumber[];
}
export type PlayerWithdrawEvent = TypedEvent<
  [BigNumber, string[], BigNumber[]],
  PlayerWithdrawEventObject
>;

export type PlayerWithdrawEventFilter = TypedEventFilter<PlayerWithdrawEvent>;

export interface ReleaseVestingEventObject {
  date: BigNumber;
  vestingIndex: BigNumber;
}
export type ReleaseVestingEvent = TypedEvent<
  [BigNumber, BigNumber],
  ReleaseVestingEventObject
>;

export type ReleaseVestingEventFilter = TypedEventFilter<ReleaseVestingEvent>;

export interface WithdrawEventObject {
  date: BigNumber;
  amount: BigNumber;
}
export type WithdrawEvent = TypedEvent<
  [BigNumber, BigNumber],
  WithdrawEventObject
>;

export type WithdrawEventFilter = TypedEventFilter<WithdrawEvent>;

export interface PlayToEarnVault extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PlayToEarnVaultInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    currentVestingIndex(overrides?: CallOverrides): Promise<[BigNumber]>;

    depositRecords(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    depositTokens(
      _amount: PromiseOrValue<BigNumberish>,
      _tokenHolder: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAvailableAmountForWithdraw(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _amount: BigNumber }>;

    getVestingData(
      overrides?: CallOverrides
    ): Promise<[Vault.LockedTokenStructOutput[]]>;

    lockTokens(
      _totalAmount: PromiseOrValue<BigNumberish>,
      _initialRelease: PromiseOrValue<BigNumberish>,
      _lockDurationInDays: PromiseOrValue<BigNumberish>,
      _countOfVestings: PromiseOrValue<BigNumberish>,
      _releaseFrequencyInDays: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    playToEarnServiceAddress(overrides?: CallOverrides): Promise<[string]>;

    playerDepositTokensToGame(
      _playfabTxId: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    playerWithdrawTokensFromGame(
      _players: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    proxyAddress(overrides?: CallOverrides): Promise<[string]>;

    releasedAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    setPlayToEarnServiceAddress(
      _newAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    soulsTokenAddress(overrides?: CallOverrides): Promise<[string]>;

    tokenVestings(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, boolean] & {
        amount: BigNumber;
        unlockTime: BigNumber;
        released: boolean;
      }
    >;

    totalWithdrawnAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    vaultName(overrides?: CallOverrides): Promise<[string]>;

    withdrawTokens(
      arg0: PromiseOrValue<string>[],
      arg1: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  currentVestingIndex(overrides?: CallOverrides): Promise<BigNumber>;

  depositRecords(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  depositTokens(
    _amount: PromiseOrValue<BigNumberish>,
    _tokenHolder: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAvailableAmountForWithdraw(overrides?: CallOverrides): Promise<BigNumber>;

  getVestingData(
    overrides?: CallOverrides
  ): Promise<Vault.LockedTokenStructOutput[]>;

  lockTokens(
    _totalAmount: PromiseOrValue<BigNumberish>,
    _initialRelease: PromiseOrValue<BigNumberish>,
    _lockDurationInDays: PromiseOrValue<BigNumberish>,
    _countOfVestings: PromiseOrValue<BigNumberish>,
    _releaseFrequencyInDays: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  playToEarnServiceAddress(overrides?: CallOverrides): Promise<string>;

  playerDepositTokensToGame(
    _playfabTxId: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  playerWithdrawTokensFromGame(
    _players: PromiseOrValue<string>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  proxyAddress(overrides?: CallOverrides): Promise<string>;

  releasedAmount(overrides?: CallOverrides): Promise<BigNumber>;

  setPlayToEarnServiceAddress(
    _newAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  soulsTokenAddress(overrides?: CallOverrides): Promise<string>;

  tokenVestings(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, boolean] & {
      amount: BigNumber;
      unlockTime: BigNumber;
      released: boolean;
    }
  >;

  totalWithdrawnAmount(overrides?: CallOverrides): Promise<BigNumber>;

  vaultName(overrides?: CallOverrides): Promise<string>;

  withdrawTokens(
    arg0: PromiseOrValue<string>[],
    arg1: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    currentVestingIndex(overrides?: CallOverrides): Promise<BigNumber>;

    depositRecords(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    depositTokens(
      _amount: PromiseOrValue<BigNumberish>,
      _tokenHolder: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getAvailableAmountForWithdraw(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVestingData(
      overrides?: CallOverrides
    ): Promise<Vault.LockedTokenStructOutput[]>;

    lockTokens(
      _totalAmount: PromiseOrValue<BigNumberish>,
      _initialRelease: PromiseOrValue<BigNumberish>,
      _lockDurationInDays: PromiseOrValue<BigNumberish>,
      _countOfVestings: PromiseOrValue<BigNumberish>,
      _releaseFrequencyInDays: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    playToEarnServiceAddress(overrides?: CallOverrides): Promise<string>;

    playerDepositTokensToGame(
      _playfabTxId: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    playerWithdrawTokensFromGame(
      _players: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    proxyAddress(overrides?: CallOverrides): Promise<string>;

    releasedAmount(overrides?: CallOverrides): Promise<BigNumber>;

    setPlayToEarnServiceAddress(
      _newAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    soulsTokenAddress(overrides?: CallOverrides): Promise<string>;

    tokenVestings(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, boolean] & {
        amount: BigNumber;
        unlockTime: BigNumber;
        released: boolean;
      }
    >;

    totalWithdrawnAmount(overrides?: CallOverrides): Promise<BigNumber>;

    vaultName(overrides?: CallOverrides): Promise<string>;

    withdrawTokens(
      arg0: PromiseOrValue<string>[],
      arg1: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DepositTokens(uint256,uint256)"(
      date?: PromiseOrValue<BigNumberish> | null,
      _amount?: null
    ): DepositTokensEventFilter;
    DepositTokens(
      date?: PromiseOrValue<BigNumberish> | null,
      _amount?: null
    ): DepositTokensEventFilter;

    "PlayerDeposit(uint256,string,uint256)"(
      timestamp?: PromiseOrValue<BigNumberish> | null,
      playfabTxId?: PromiseOrValue<string> | null,
      amount?: PromiseOrValue<BigNumberish> | null
    ): PlayerDepositEventFilter;
    PlayerDeposit(
      timestamp?: PromiseOrValue<BigNumberish> | null,
      playfabTxId?: PromiseOrValue<string> | null,
      amount?: PromiseOrValue<BigNumberish> | null
    ): PlayerDepositEventFilter;

    "PlayerWithdraw(uint256,address[],uint256[])"(
      timestamp?: PromiseOrValue<BigNumberish> | null,
      playerWallet?: PromiseOrValue<string>[] | null,
      amount?: PromiseOrValue<BigNumberish>[] | null
    ): PlayerWithdrawEventFilter;
    PlayerWithdraw(
      timestamp?: PromiseOrValue<BigNumberish> | null,
      playerWallet?: PromiseOrValue<string>[] | null,
      amount?: PromiseOrValue<BigNumberish>[] | null
    ): PlayerWithdrawEventFilter;

    "ReleaseVesting(uint256,uint256)"(
      date?: PromiseOrValue<BigNumberish> | null,
      vestingIndex?: PromiseOrValue<BigNumberish> | null
    ): ReleaseVestingEventFilter;
    ReleaseVesting(
      date?: PromiseOrValue<BigNumberish> | null,
      vestingIndex?: PromiseOrValue<BigNumberish> | null
    ): ReleaseVestingEventFilter;

    "Withdraw(uint256,uint256)"(
      date?: PromiseOrValue<BigNumberish> | null,
      amount?: PromiseOrValue<BigNumberish> | null
    ): WithdrawEventFilter;
    Withdraw(
      date?: PromiseOrValue<BigNumberish> | null,
      amount?: PromiseOrValue<BigNumberish> | null
    ): WithdrawEventFilter;
  };

  estimateGas: {
    currentVestingIndex(overrides?: CallOverrides): Promise<BigNumber>;

    depositRecords(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    depositTokens(
      _amount: PromiseOrValue<BigNumberish>,
      _tokenHolder: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAvailableAmountForWithdraw(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVestingData(overrides?: CallOverrides): Promise<BigNumber>;

    lockTokens(
      _totalAmount: PromiseOrValue<BigNumberish>,
      _initialRelease: PromiseOrValue<BigNumberish>,
      _lockDurationInDays: PromiseOrValue<BigNumberish>,
      _countOfVestings: PromiseOrValue<BigNumberish>,
      _releaseFrequencyInDays: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    playToEarnServiceAddress(overrides?: CallOverrides): Promise<BigNumber>;

    playerDepositTokensToGame(
      _playfabTxId: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    playerWithdrawTokensFromGame(
      _players: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    proxyAddress(overrides?: CallOverrides): Promise<BigNumber>;

    releasedAmount(overrides?: CallOverrides): Promise<BigNumber>;

    setPlayToEarnServiceAddress(
      _newAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    soulsTokenAddress(overrides?: CallOverrides): Promise<BigNumber>;

    tokenVestings(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalWithdrawnAmount(overrides?: CallOverrides): Promise<BigNumber>;

    vaultName(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawTokens(
      arg0: PromiseOrValue<string>[],
      arg1: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    currentVestingIndex(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    depositRecords(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    depositTokens(
      _amount: PromiseOrValue<BigNumberish>,
      _tokenHolder: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAvailableAmountForWithdraw(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVestingData(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lockTokens(
      _totalAmount: PromiseOrValue<BigNumberish>,
      _initialRelease: PromiseOrValue<BigNumberish>,
      _lockDurationInDays: PromiseOrValue<BigNumberish>,
      _countOfVestings: PromiseOrValue<BigNumberish>,
      _releaseFrequencyInDays: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    playToEarnServiceAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    playerDepositTokensToGame(
      _playfabTxId: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    playerWithdrawTokensFromGame(
      _players: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    proxyAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    releasedAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setPlayToEarnServiceAddress(
      _newAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    soulsTokenAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenVestings(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalWithdrawnAmount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    vaultName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawTokens(
      arg0: PromiseOrValue<string>[],
      arg1: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
