/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ILiquidityVaultInterface extends utils.Interface {
  functions: {
    "BUSDAmountForInitialLiquidity()": FunctionFragment;
    "getDEXPairAddress()": FunctionFragment;
    "lockTokens(uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "lockTokens(uint256)": FunctionFragment;
    "withdrawMarketMakerShare(address,uint256)": FunctionFragment;
    "withdrawTokens(address[],uint256[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "BUSDAmountForInitialLiquidity"
      | "getDEXPairAddress"
      | "lockTokens(uint256,uint256,uint256,uint256,uint256)"
      | "lockTokens(uint256)"
      | "withdrawMarketMakerShare"
      | "withdrawTokens"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "BUSDAmountForInitialLiquidity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDEXPairAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockTokens(uint256,uint256,uint256,uint256,uint256)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "lockTokens(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawMarketMakerShare",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawTokens",
    values: [PromiseOrValue<string>[], PromiseOrValue<BigNumberish>[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "BUSDAmountForInitialLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDEXPairAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockTokens(uint256,uint256,uint256,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockTokens(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawMarketMakerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawTokens",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ILiquidityVault extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ILiquidityVaultInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    BUSDAmountForInitialLiquidity(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getDEXPairAddress(overrides?: CallOverrides): Promise<[string]>;

    "lockTokens(uint256,uint256,uint256,uint256,uint256)"(
      _totalAmount: PromiseOrValue<BigNumberish>,
      _initialRelease: PromiseOrValue<BigNumberish>,
      _lockDurationInDays: PromiseOrValue<BigNumberish>,
      _countOfVesting: PromiseOrValue<BigNumberish>,
      _releaseFrequencyInDays: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "lockTokens(uint256)"(
      _totalAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawMarketMakerShare(
      _receiver: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawTokens(
      _receivers: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  BUSDAmountForInitialLiquidity(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getDEXPairAddress(overrides?: CallOverrides): Promise<string>;

  "lockTokens(uint256,uint256,uint256,uint256,uint256)"(
    _totalAmount: PromiseOrValue<BigNumberish>,
    _initialRelease: PromiseOrValue<BigNumberish>,
    _lockDurationInDays: PromiseOrValue<BigNumberish>,
    _countOfVesting: PromiseOrValue<BigNumberish>,
    _releaseFrequencyInDays: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "lockTokens(uint256)"(
    _totalAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawMarketMakerShare(
    _receiver: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawTokens(
    _receivers: PromiseOrValue<string>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    BUSDAmountForInitialLiquidity(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDEXPairAddress(overrides?: CallOverrides): Promise<string>;

    "lockTokens(uint256,uint256,uint256,uint256,uint256)"(
      _totalAmount: PromiseOrValue<BigNumberish>,
      _initialRelease: PromiseOrValue<BigNumberish>,
      _lockDurationInDays: PromiseOrValue<BigNumberish>,
      _countOfVesting: PromiseOrValue<BigNumberish>,
      _releaseFrequencyInDays: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "lockTokens(uint256)"(
      _totalAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawMarketMakerShare(
      _receiver: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawTokens(
      _receivers: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    BUSDAmountForInitialLiquidity(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getDEXPairAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "lockTokens(uint256,uint256,uint256,uint256,uint256)"(
      _totalAmount: PromiseOrValue<BigNumberish>,
      _initialRelease: PromiseOrValue<BigNumberish>,
      _lockDurationInDays: PromiseOrValue<BigNumberish>,
      _countOfVesting: PromiseOrValue<BigNumberish>,
      _releaseFrequencyInDays: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "lockTokens(uint256)"(
      _totalAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawMarketMakerShare(
      _receiver: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawTokens(
      _receivers: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BUSDAmountForInitialLiquidity(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getDEXPairAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "lockTokens(uint256,uint256,uint256,uint256,uint256)"(
      _totalAmount: PromiseOrValue<BigNumberish>,
      _initialRelease: PromiseOrValue<BigNumberish>,
      _lockDurationInDays: PromiseOrValue<BigNumberish>,
      _countOfVesting: PromiseOrValue<BigNumberish>,
      _releaseFrequencyInDays: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "lockTokens(uint256)"(
      _totalAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawMarketMakerShare(
      _receiver: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawTokens(
      _receivers: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
